### ISSUE TITLE
[Rule] gosec G104 (CWE-703): Errors unhandled rule

### ISSUE THREAD

**Issue by zabbal** [returntocorp/sgrep-rules#1149]
**Rule Description**
Errors unhandled rule.

*What does this rule intend to find?*
Catch golang code with missing error handling.

**Examples or references**
The equivalent of https://github.com/securego/gosec/ G104 rule.

*Put an example or references here*
Sample code which triggers it:
`
 func setLogConfig() {
       flag.Set("logtostderr", "true") // this line triggers the rules
       flag.Parse()
`

**Additional information**
I've also tried "p/dgryski.semgrep-go" rulesset which seems to have additional error handling checks but no findings either.

*More information that would help someone write this rule!*
I've noticed the difference between check with "p/gosec" ruleset and an actual gosec run.

**PR Checklist**
- [ ] This ticket has links, references, or examples.
- [ ] The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- [ ] The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

- [ ] After the PR has been reviewed and approved, merge the rule and close this ticket! Thanks for contributing!

**Comment by colleend** [comment]
Hi zabbal,

Thanks for submitting this rule request! I attempted to write a pattern that does something similar to what gosec rule G104 does using the following semgrep pattern: https://semgrep.dev/s/Avqp/. 

However, our typed metavariables are still experimental -- I have submitted an issue https://github.com/returntocorp/semgrep/issues/2747 for this specific rule, and we will be able to successfully have this rule written once the issue is fixed. 

Of course, this is not the only way to write the rule. I have also attempted to write the rule by specifying the function return type, but this will require https://github.com/returntocorp/semgrep/issues/2746 to be fixed before we can successfully write this rule. 

Thanks so much for your patience & understanding!
