### ISSUE TITLE
[Rule] New PHP rules

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/sgrep-rules#1164]
**Rule Description**

[Modern PHP Security Part 1: bug classes | Detectify Labs](https://labs.detectify.com/2020/08/13/modern-php-security-part-1-bug-classes/)
*What does this rule intend to find?*

**Examples or references**

*Put an example or references here*

**Additional information**

*More information that would help someone write this rule!*

**PR Checklist**
- [ ] This ticket has links, references, or examples.
- [ ] The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- [ ] The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

- [ ] After the PR has been reviewed and approved, merge the rule and close this ticket! Thanks for contributing!

**Comment by Sjord** [comment]
The article mentions several PHP vulnerabilities:

## SQL injection

Vulnerable code:

```
$query = DB::table('users')->addSelect("biography->$_GET['lang']");
```

Even though there are rules for SQL injection in PHP, this form is currently not detected by semgrep. The example code is specific to [Laravel](https://laravel.com/docs/8.x/queries). The parameters to methods such as `addSelect` and `selectRaw` are used directly in the query, and thus risk SQL injection.

I recommend creating a new issue: Detect Laravel-specific SQL injection on column names and raw expressions

## Deserialization via phar://

Vulnerable code:

```
if(file_exists($_GET['file'] .'tpl')) { ... }

if(filesize($_GET['file']) > 1000) { ... }

if(md5_file($_GET['file']) == ...) { ... }
```

Currently not found with semgrep. Could be a good candidate for taint mode. The risk occurs if a scheme handler (http://, phar://) is added, so the attackers needs control over the start of the string. Any file-handling method would be a vulnerable sink.

I recommend creating a new issue: Detect passing user input to file-handling methods in PHP

## Arbitrary instantiation

No vulnerable code explicitly given. If would look something like:

```
$parts = explode("/", $_SERVER['PATH_INFO']);
$controllerName = $parts[0];
$controller = new $controllerName($parts[1]);
```

This is often implemented in the framework, as opposed to the business logic, but with everyone creating their own PHP framework you can never be sure. I guess a taint-mode rule that detects user input in object instantiation could be useful.

I recommend creating a new issue: Detect user input in object instantiation in PHP

## Server-side request forgery

No vulnerable code explicitly given. It would look similar as "Deserialization via phar://" described above, and the same rule could detect both instances. No separate action required.

A partial check for SSRF is already present in [semgrep-rules/tainted-url-host.yaml at develop · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/develop/php/lang/security/injection/tainted-url-host.yaml)

## Server-side template injection

No vulnerable code explicitly given. Template injection happens when user input ends up in a template, perhaps because the templating function is run twice. This could be hard to detect within a single source file, and would be specific to the templating engine. Most frameworks I know handle templating automatically, and don't need to be called explicitly, reducing the possibility of template injection.

There's already a rule for JS: [semgrep-rules/server_side_template_injection.yaml at 2b32e459b0e9baf8f41ab881d0bdf6cf9a72799f · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/blob/2b32e459b0e9baf8f41ab881d0bdf6cf9a72799f/contrib/nodejsscan/server_side_template_injection.yaml) 

I recommend a new issue to create a rule for the most popular template engine, Twig: Detect user input in template content in Twig for PHP to avoid template injection

**Comment by Sjord** [comment]
I added a rule to detect user input in file handling functions: [Add rule to detect tainted filenames in PHP by Sjord · Pull Request #1697 · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/pull/1697)

This relates to both *Deserialization via phar://* and *Server-side request forgery* as described above.

**Comment by Sjord** [comment]
Regarding arbitrary instantation, it may be interesting to find calls to [ReflectionClass::newInstanceArgs](https://www.php.net/manual/en/reflectionclass.newinstanceargs.php).

**Comment by Sjord** [comment]
[Detect SQL injection with Laravel ORM methods by Sjord · Pull Request #1737 · returntocorp/semgrep-rules](https://github.com/returntocorp/semgrep-rules/pull/1737)
