### ISSUE TITLE
go.lang.security.audit.sqli.pg-orm-sqli false positive

### ISSUE THREAD

**Issue by tuhaolam** [returntocorp/sgrep-rules#1263]
**Describe the bug**
Maybe what the ellipsis ... can do is not enough, for example, it can not support 'abc like "%d"', thus result to be false positive. And how can we do if there is many placeholders in a literal string like 'a like "a%s" and "%d"'? I think the following rule in go.lang.security.audit.sqli.pg-orm-sqli maybe too easy to be false positive because of too broad.
```
 16         - pattern-inside: |
 17             $QUERY = fmt.Sprintf("...", $PARAM1, ...)
```
**To Reproduce**
```
sqli/1.go
severity:warning rule:home.mqq.user.tulliuslin.scanner.semgrep-rules.go.lang.security.audit.sqli.pg-orm-sqli: Detected string concatenation with a non-literal variable in a go-pg ORM
SQL statement. This could lead to SQL injection if the variable is user-controlled
and not properly sanitized. In order to prevent SQL injection,
do not use strings concatenated with user-controlled input.
Instead, use parameterized statements.

1: err := s.GetModel().Where(fmt.Sprintf("ref_id=%d", refID)).
2:        Where(fmt.Sprintf("type=%d", LogTypeOm)).OrderBy("id desc").Find(&ret)
--------------------------------------------------------------------------------
1: err := s.GetModel().Where(fmt.Sprintf("ref_id=%d", refID)).
```

```go
#cat sqli/1.go
 err := s.GetModel().Where(fmt.Sprintf("ref_id=%d", refID)).
        Where(fmt.Sprintf("type=%d", LogTypeOm)).OrderBy("id desc").Find(&ret)
```
**Expected behavior**
Fix the above issue with a better rule, even update the ellipsis ... to do more things.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [x] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional Context**
NO

**Comment by mschwager** [comment]
Hi there,

It looks like @colleend recently added this rule. @colleend can we fix this FP?

**Comment by colleend** [comment]
Thanks for tagging me, and thanks for filing this issue! Sorry that you ran into this FP and that it's inconveniencing you at this moment.

Unfortunately, I don't think we'll fix this FP because:
1. This is a secure-defaults rule, meaning that it is here to encourage the usage of pg ORM in a certain secure manner. Therefore, it's going to catch all cases of string-concatenation that occurs in the ORM clauses ("Where", "Select", etc). It's here to nudge users to instead use parameterization (so, in the case of the code that it matched on):
```s.GetModel().Where('type=?', LogTypeOm)```
and 
  ```
  s.GetModel().Where("ref_id=?", refID).
          Where("type=?", LogTypeOm).OrderBy("id desc").Find(&ret)
  ```
These secure-defaults rules are meant to encourage safe coding practices so I would suggest moving towards this!
2. In this case in particular, we could use a metavariable instead of the ellipsis in the `fmt.Sprintf` patterns and then use metavariable-regex to filter out cases where '%d' happens but not '%s'. However, I've run into some issues with our tool having multiple `metavariable-regex`s in the pattern, and there might need to be more engineering work to do there before this can happen. 

Thanks so much for your patience and hope this was helpful!

**Comment by tuhaolam** [comment]
Thanks all of you @colleend @mschwager, the reply is very useful.

**Comment by colleend** [comment]
Awesome, glad that you found it helpful, and, again, thanks for filing this issue 😁
